---
title: "G4 Final Presentation Outline"
author: "Qianruo Tan, Jia Xia, Yuxiao Chen, Jiawei Zhang"
format: revealjs
jupyter: python3
---

## Introduction

This presentation simply illustrate our group's outline.
PACSOY_502009_G4

This presentation supported by .qmd file, revealjs document.
**Quarto + Reveal.js**.

---



## Field of study

Choose one of the following:

- Amazon Logistics Warehousing (operation)

- Seattle government open data

    - Transportation

    - Public health 
    https://www.kaggle.com/datasets/cdc/behavioral-risk-factor-surveillance-system/data

    - Air pollution
    https://www.kaggle.com/datasets/sogun3/uspollution/data
    https://aqs.epa.gov/aqsweb/airdata/download_files.html



## Source of dataset 

- Seattle government dataset

    - website and description needed (for citation use)



## Topic of our study

- 



## Research Methods

- Horizontal comparison of the effectiveness of different methods
    - 要做很多重复实验，去横向对比
横向做很多次试验，对比ETC UCB TS。需要大量时间成本去进行运行和调试。

- Adjusting one of the algorithms to maximize its effectiveness
    - 需要研究更深层的理论
纵向做深度研究
现在学的是offline evaluation
更深一步可以去做offline policy evaluation
可以使用Inverse Propensity Score (IPS)、Doubly Robust (DR)等办法
（类似于supervised learning里面的用历史数据评估模型（like split 80% for learning, 20% for testing）

